// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: messages-sp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction ID (SHA256 hash)
type XtID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // 32-byte SHA256 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XtID) Reset() {
	*x = XtID{}
	mi := &file_messages_sp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XtID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XtID) ProtoMessage() {}

func (x *XtID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XtID.ProtoReflect.Descriptor instead.
func (*XtID) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{0}
}

func (x *XtID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Cross-chain transaction request
type XTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionRequest  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XTRequest) Reset() {
	*x = XTRequest{}
	mi := &file_messages_sp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XTRequest) ProtoMessage() {}

func (x *XTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XTRequest.ProtoReflect.Descriptor instead.
func (*XTRequest) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{1}
}

func (x *XTRequest) GetTransactions() []*TransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Transaction   [][]byte               `protobuf:"bytes,2,rep,name=transaction,proto3" json:"transaction,omitempty"` // RLP encoded Ethereum transactions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_messages_sp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *TransactionRequest) GetTransaction() [][]byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// 2PC Vote message from a sequencer to the SP
type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderChainId []byte                 `protobuf:"bytes,1,opt,name=sender_chain_id,json=senderChainId,proto3" json:"sender_chain_id,omitempty"` // Which chain is voting
	XtId          *XtID                  `protobuf:"bytes,2,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"`                              // Transaction ID
	Vote          bool                   `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`                                         // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_messages_sp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{3}
}

func (x *Vote) GetSenderChainId() []byte {
	if x != nil {
		return x.SenderChainId
	}
	return nil
}

func (x *Vote) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

// 2PC Decision message from the SP to sequencers
type Decided struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XtId          *XtID                  `protobuf:"bytes,1,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"` // Transaction ID
	Decision      bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`    // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decided) Reset() {
	*x = Decided{}
	mi := &file_messages_sp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decided) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decided) ProtoMessage() {}

func (x *Decided) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decided.ProtoReflect.Descriptor instead.
func (*Decided) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{4}
}

func (x *Decided) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *Decided) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

// Block submission from a sequencer to the SP
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                     // Which chain's block
	BlockData     []byte                 `protobuf:"bytes,2,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`               // The actual block data
	IncludedXtIds []*XtID                `protobuf:"bytes,3,rep,name=included_xt_ids,json=includedXtIds,proto3" json:"included_xt_ids,omitempty"` // Which xTs are included
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_messages_sp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *Block) GetBlockData() []byte {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *Block) GetIncludedXtIds() []*XtID {
	if x != nil {
		return x.IncludedXtIds
	}
	return nil
}

// Direct CIRC message exchange between sequencers (without SP involvement)
type CIRCMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceChain      []byte                 `protobuf:"bytes,1,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	DestinationChain []byte                 `protobuf:"bytes,2,opt,name=destination_chain,json=destinationChain,proto3" json:"destination_chain,omitempty"`
	Source           [][]byte               `protobuf:"bytes,3,rep,name=source,proto3" json:"source,omitempty"`
	Receiver         [][]byte               `protobuf:"bytes,4,rep,name=receiver,proto3" json:"receiver,omitempty"`
	XtId             *XtID                  `protobuf:"bytes,5,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"`
	Label            string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Data             [][]byte               `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty"` // ABI encoded data
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CIRCMessage) Reset() {
	*x = CIRCMessage{}
	mi := &file_messages_sp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIRCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIRCMessage) ProtoMessage() {}

func (x *CIRCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIRCMessage.ProtoReflect.Descriptor instead.
func (*CIRCMessage) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{6}
}

func (x *CIRCMessage) GetSourceChain() []byte {
	if x != nil {
		return x.SourceChain
	}
	return nil
}

func (x *CIRCMessage) GetDestinationChain() []byte {
	if x != nil {
		return x.DestinationChain
	}
	return nil
}

func (x *CIRCMessage) GetSource() [][]byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CIRCMessage) GetReceiver() [][]byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *CIRCMessage) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *CIRCMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CIRCMessage) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Wrapper for all messages
type Message struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Identifier of the sender
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_XtRequest
	//	*Message_Vote
	//	*Message_Decided
	//	*Message_Block
	//	*Message_CircMessage
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_sp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_sp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_sp_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetXtRequest() *XTRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_XtRequest); ok {
			return x.XtRequest
		}
	}
	return nil
}

func (x *Message) GetVote() *Vote {
	if x != nil {
		if x, ok := x.Payload.(*Message_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *Message) GetDecided() *Decided {
	if x != nil {
		if x, ok := x.Payload.(*Message_Decided); ok {
			return x.Decided
		}
	}
	return nil
}

func (x *Message) GetBlock() *Block {
	if x != nil {
		if x, ok := x.Payload.(*Message_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *Message) GetCircMessage() *CIRCMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_CircMessage); ok {
			return x.CircMessage
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_XtRequest struct {
	XtRequest *XTRequest `protobuf:"bytes,2,opt,name=xt_request,json=xtRequest,proto3,oneof"`
}

type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,3,opt,name=vote,proto3,oneof"`
}

type Message_Decided struct {
	Decided *Decided `protobuf:"bytes,4,opt,name=decided,proto3,oneof"`
}

type Message_Block struct {
	Block *Block `protobuf:"bytes,5,opt,name=block,proto3,oneof"`
}

type Message_CircMessage struct {
	CircMessage *CIRCMessage `protobuf:"bytes,6,opt,name=circ_message,json=circMessage,proto3,oneof"`
}

func (*Message_XtRequest) isMessage_Payload() {}

func (*Message_Vote) isMessage_Payload() {}

func (*Message_Decided) isMessage_Payload() {}

func (*Message_Block) isMessage_Payload() {}

func (*Message_CircMessage) isMessage_Payload() {}

var File_messages_sp_proto protoreflect.FileDescriptor

const file_messages_sp_proto_rawDesc = "" +
	"\n" +
	"\x11messages-sp.proto\x12\x03poc\"\x1a\n" +
	"\x04XtID\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"H\n" +
	"\tXTRequest\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.poc.TransactionRequestR\ftransactions\"Q\n" +
	"\x12TransactionRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12 \n" +
	"\vtransaction\x18\x02 \x03(\fR\vtransaction\"b\n" +
	"\x04Vote\x12&\n" +
	"\x0fsender_chain_id\x18\x01 \x01(\fR\rsenderChainId\x12\x1e\n" +
	"\x05xt_id\x18\x02 \x01(\v2\t.poc.XtIDR\x04xtId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\bR\x04vote\"E\n" +
	"\aDecided\x12\x1e\n" +
	"\x05xt_id\x18\x01 \x01(\v2\t.poc.XtIDR\x04xtId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\"t\n" +
	"\x05Block\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x1d\n" +
	"\n" +
	"block_data\x18\x02 \x01(\fR\tblockData\x121\n" +
	"\x0fincluded_xt_ids\x18\x03 \x03(\v2\t.poc.XtIDR\rincludedXtIds\"\xdb\x01\n" +
	"\vCIRCMessage\x12!\n" +
	"\fsource_chain\x18\x01 \x01(\fR\vsourceChain\x12+\n" +
	"\x11destination_chain\x18\x02 \x01(\fR\x10destinationChain\x12\x16\n" +
	"\x06source\x18\x03 \x03(\fR\x06source\x12\x1a\n" +
	"\breceiver\x18\x04 \x03(\fR\breceiver\x12\x1e\n" +
	"\x05xt_id\x18\x05 \x01(\v2\t.poc.XtIDR\x04xtId\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\a \x03(\fR\x04data\"\x88\x02\n" +
	"\aMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12/\n" +
	"\n" +
	"xt_request\x18\x02 \x01(\v2\x0e.poc.XTRequestH\x00R\txtRequest\x12\x1f\n" +
	"\x04vote\x18\x03 \x01(\v2\t.poc.VoteH\x00R\x04vote\x12(\n" +
	"\adecided\x18\x04 \x01(\v2\f.poc.DecidedH\x00R\adecided\x12\"\n" +
	"\x05block\x18\x05 \x01(\v2\n" +
	".poc.BlockH\x00R\x05block\x125\n" +
	"\fcirc_message\x18\x06 \x01(\v2\x10.poc.CIRCMessageH\x00R\vcircMessageB\t\n" +
	"\apayloadB6Z4github.com/ethereum/go-ethereum/internal/sp/protob\x06proto3"

var (
	file_messages_sp_proto_rawDescOnce sync.Once
	file_messages_sp_proto_rawDescData []byte
)

func file_messages_sp_proto_rawDescGZIP() []byte {
	file_messages_sp_proto_rawDescOnce.Do(func() {
		file_messages_sp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_sp_proto_rawDesc), len(file_messages_sp_proto_rawDesc)))
	})
	return file_messages_sp_proto_rawDescData
}

var file_messages_sp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_sp_proto_goTypes = []any{
	(*XtID)(nil),               // 0: poc.XtID
	(*XTRequest)(nil),          // 1: poc.XTRequest
	(*TransactionRequest)(nil), // 2: poc.TransactionRequest
	(*Vote)(nil),               // 3: poc.Vote
	(*Decided)(nil),            // 4: poc.Decided
	(*Block)(nil),              // 5: poc.Block
	(*CIRCMessage)(nil),        // 6: poc.CIRCMessage
	(*Message)(nil),            // 7: poc.Message
}
var file_messages_sp_proto_depIdxs = []int32{
	2,  // 0: poc.XTRequest.transactions:type_name -> poc.TransactionRequest
	0,  // 1: poc.Vote.xt_id:type_name -> poc.XtID
	0,  // 2: poc.Decided.xt_id:type_name -> poc.XtID
	0,  // 3: poc.Block.included_xt_ids:type_name -> poc.XtID
	0,  // 4: poc.CIRCMessage.xt_id:type_name -> poc.XtID
	1,  // 5: poc.Message.xt_request:type_name -> poc.XTRequest
	3,  // 6: poc.Message.vote:type_name -> poc.Vote
	4,  // 7: poc.Message.decided:type_name -> poc.Decided
	5,  // 8: poc.Message.block:type_name -> poc.Block
	6,  // 9: poc.Message.circ_message:type_name -> poc.CIRCMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_sp_proto_init() }
func file_messages_sp_proto_init() {
	if File_messages_sp_proto != nil {
		return
	}
	file_messages_sp_proto_msgTypes[7].OneofWrappers = []any{
		(*Message_XtRequest)(nil),
		(*Message_Vote)(nil),
		(*Message_Decided)(nil),
		(*Message_Block)(nil),
		(*Message_CircMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_sp_proto_rawDesc), len(file_messages_sp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_sp_proto_goTypes,
		DependencyIndexes: file_messages_sp_proto_depIdxs,
		MessageInfos:      file_messages_sp_proto_msgTypes,
	}.Build()
	File_messages_sp_proto = out.File
	file_messages_sp_proto_goTypes = nil
	file_messages_sp_proto_depIdxs = nil
}
